# Looks
[env]
term = "xterm-256color"

# [colors.bright]
# black = "0x565656"
# blue = "0x49a4f8"
# cyan = "0x99faf2"
# green = "0xc0e17d"
# magenta = "0xa47de9"
# red = "0xec5357"
# white = "0xffffff"
# yellow = "0xf9da6a"
#
# [colors.normal]
# black = "0x2e2e2e"
# blue = "0x47a0f3"
# cyan = "0x64dbed"
# green = "0xabe047"
# magenta = "0x7b5cb0"
# red = "0xeb4129"
# white = "0xe5e9f0"
# yellow = "0xf6c744"
#
# [colors.primary]
# background = "#000000"
# foreground = "0xfffbf6"

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"

### CATPUCCIN

# [colors.primary]
# background = "#000000"
# foreground = "#CDD6F4"
# dim_foreground = "#CDD6F4"
# bright_foreground = "#CDD6F4"
#
# [colors.vi_mode_cursor]
# text = "#1E1E2E"
# cursor = "#B4BEFE"
#
# [colors.search.matches]
# foreground = "#1E1E2E"
# background = "#A6ADC8"
#
# [colors.search.focused_match]
# foreground = "#1E1E2E"
# background = "#A6E3A1"
#
# [colors.footer_bar]
# foreground = "#1E1E2E"
# background = "#A6ADC8"
#
# [colors.hints.start]
# foreground = "#1E1E2E"
# background = "#F9E2AF"
#
# [colors.hints.end]
# foreground = "#1E1E2E"
# background = "#A6ADC8"
#
# [colors.selection]
# text = "#1E1E2E"
# background = "#F5E0DC"
#
# [colors.normal]
# black = "#45475A"
# red = "#F38BA8"
# green = "#A6E3A1"
# yellow = "#F9E2AF"
# blue = "#89B4FA"
# magenta = "#F5C2E7"
# cyan = "#94E2D5"
# white = "#BAC2DE"
#
# [colors.bright]
# black = "#585B70"
# red = "#F38BA8"
# green = "#A6E3A1"
# yellow = "#F9E2AF"
# blue = "#89B4FA"
# magenta = "#F5C2E7"
# cyan = "#94E2D5"
# white = "#A6ADC8"
#
# [colors.dim]
# black = "#45475A"
# red = "#F38BA8"
# green = "#A6E3A1"
# yellow = "#F9E2AF"
# blue = "#89B4FA"
# magenta = "#F5C2E7"
# cyan = "#94E2D5"
# white = "#BAC2DE"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#FAB387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#F5E0DC"


### ONEDARK

[colors.primary]
background = "0x111111"
foreground = "0xabb2bf"
bright_foreground = "0xe6efff"

[colors.normal]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xe6efff"

[colors.dim]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0x828791"

[font]
size = 9.5

# [font.bold]
# family = "Hasklug Nerd Font"
# style = "Regular"
#
# [font.italic]
# family = "Hasklug Nerd Font"
# style = "Regular"
#
# [font.normal]
# family = "Hasklug Nerd Font"
# style = "Regular"

[font.bold]
family = "Source Code Pro"
style = "Medium"

[font.italic]
family = "Source Code Pro"
style = "Medium"

[font.normal]
family = "Source Code Pro"
style = "Medium"

# [font.bold]
# family = "Berkeley Mono"
# style = "Regular"
#
# [font.italic]
# family = "Berkeley Mono"
# style = "Regular"
#
# [font.normal]
# family = "Berkeley Mono"
# style = "Regular"

# [font.bold]
# family = "Fira Mono"
# style = "Regular"
#
# [font.italic]
# family = "Fira Mono"
# style = "Regular"
#
# [font.normal]
# family = "Fira Mono"
# style = "Regular"

# [font.bold]
# family = "jetBrains Mono"
# style = "Regular"
#
# [font.italic]
# family = "jetBrains Mono"
# style = "Regular"
#
# [font.normal]
# family = "jetBrains Mono"
# style = "Regular"

[window]
opacity = 1


# keyboard binding for ctrl + shift chars
# code from https://github.com/alacritty/alacritty/issues/7892#issuecomment-2041265313
[keyboard]
bindings = [
{ key = "T", mods = "Control | Shift", chars = "\u001b[84;6u" },
{ key = "B", mods = "Control | Shift", chars = "\u001b[66;6u" }
]
