# Looks
[env]
term = "xterm-256color"

# [colors.bright]
# black = "0x565656"
# blue = "0x49a4f8"
# cyan = "0x99faf2"
# green = "0xc0e17d"
# magenta = "0xa47de9"
# red = "0xec5357"
# white = "0xffffff"
# yellow = "0xf9da6a"
#
# [colors.normal]
# black = "0x2e2e2e"
# blue = "0x47a0f3"
# cyan = "0x64dbed"
# green = "0xabe047"
# magenta = "0x7b5cb0"
# red = "0xeb4129"
# white = "0xe5e9f0"
# yellow = "0xf6c744"
#
# [colors.primary]
# background = "#000000"
# foreground = "0xfffbf6"

[colors.primary]
background = "#000000"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[font]
size = 9.5

[font.bold]
family = "Hasklug Nerd Font"
style = "Regular"

[font.italic]
family = "Hasklug Nerd Font"
style = "Regular"

[font.normal]
family = "Hasklug Nerd Font"
style = "Regular"

# [font.bold]
# family = "Fira Mono"
# style = "Regular"
#
# [font.italic]
# family = "Fira Mono"
# style = "Regular"
#
# [font.normal]
# family = "Fira Mono"
# style = "Regular"

[window]
opacity = 1
