#!/bin/bash

alias ls="ls --color -G --group-directories-first"
alias ll="ls -la"

alias n="nvim ."

cd() {
    builtin cd "${@:-$HOME}" && ls
}

# Edit/Source zsh config
alias ez='nvim ~/.zsh_profile'
alias sz='source ~/.zshrc'

# Project helpers
alias ..='cd ../'
alias ...='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'
alias .6='cd ../../../../../../'

#for running detached processes
run_detached() {
    nohup "$@" </dev/null >/dev/null 2>&1 &
    disown
}

# for todoist-cli
# write td with the entire line as input no worries
function addTodoFunc() {
	todoist-cli add --date today "$*";
	exit;
};

alias td='addTodoFunc'
alias tdl='todoist-cli list'

